/**
 * Integration fixtures. They are generated by runTests.ts in its own process BEFORE VS Code
 * starts: generating hundreds of MB inside the extension host skews timing and RSS.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { generateFixture, type GenerateOptions, type GenerateResult } from '../fixtures/generate';

const MB = 1024 * 1024;

/** default: always; large: BIGVIEW_LARGE=1; huge: BIGVIEW_HUGE=1 */
export type FixtureTier = 'default' | 'large' | 'huge';

export interface FixtureSpec {
  name: string;
  tier: FixtureTier;
  opts: Omit<GenerateOptions, 'path'>;
}

export const FIXTURES = {
  small: { name: 'it-10m.log', tier: 'default', opts: { sizeBytes: 10 * MB, format: 'log', unicode: true, seed: 7, markerCount: 37 } },
  tiny: { name: 'it-default.log', tier: 'default', opts: { sizeBytes: 1 * MB, format: 'log', seed: 3 } },
  jsonl: { name: 'it-10m.jsonl', tier: 'default', opts: { sizeBytes: 10 * MB, format: 'jsonl', unicode: true, seed: 17, markerCount: 29 } },
  /** JSON Lines content behind a .log extension: detected by content. */
  jsonLog: { name: 'it-json.log', tier: 'default', opts: { sizeBytes: 1 * MB, format: 'jsonl', seed: 23 } },
  csv: { name: 'it-5m.csv', tier: 'default', opts: { sizeBytes: 5 * MB, format: 'csv', seed: 19 } },
  m200: { name: 'it-200m.log', tier: 'large', opts: { sizeBytes: 200 * MB, format: 'log', avgLineLength: 200, seed: 11 } },
  /** SPEC M3 acceptance: exactly 137 lines contain NEEDLE_MARKER. */
  g1: { name: 'it-1g.log', tier: 'large', opts: { sizeBytes: 1024 * MB, format: 'log', avgLineLength: 200, seed: 11, markerCount: 137 } },
  g5: { name: 'it-5g.log', tier: 'huge', opts: { sizeBytes: 5 * 1024 * MB, format: 'log', avgLineLength: 200, seed: 13 } },
} satisfies Record<string, FixtureSpec>;

export function enabledTiers(env: NodeJS.ProcessEnv): Set<FixtureTier> {
  const tiers = new Set<FixtureTier>(['default']);
  if (env.BIGVIEW_LARGE) tiers.add('large');
  if (env.BIGVIEW_HUGE) tiers.add('huge');
  return tiers;
}

function paths(root: string, spec: FixtureSpec): { file: string; meta: string } {
  const file = path.join(root, 'test', '.tmp', spec.name);
  return { file, meta: `${file}.json` };
}

function readMeta(root: string, spec: FixtureSpec): GenerateResult | undefined {
  const { file, meta } = paths(root, spec);
  if (!fs.existsSync(file) || !fs.existsSync(meta)) return undefined;
  const saved = JSON.parse(fs.readFileSync(meta, 'utf8')) as { key: string; result: GenerateResult };
  const fresh = saved.key === JSON.stringify(spec.opts) && fs.statSync(file).size === saved.result.bytes;
  return fresh ? { ...saved.result, path: file } : undefined;
}

/** Generates the fixture unless an up-to-date copy exists. */
export function ensureFixture(root: string, spec: FixtureSpec): GenerateResult {
  const existing = readMeta(root, spec);
  if (existing) return existing;
  const { file, meta } = paths(root, spec);
  console.log(`Generating ${spec.name} ...`);
  const result = generateFixture({ ...spec.opts, path: file });
  fs.writeFileSync(meta, JSON.stringify({ key: JSON.stringify(spec.opts), result }));
  return result;
}

/** Loads fixture metadata; never generates. */
export function loadFixture(root: string, spec: FixtureSpec): GenerateResult {
  const res = readMeta(root, spec);
  if (!res) throw new Error(`Fixture ${spec.name} missing — run via "npm run test:integration"`);
  return res;
}
